name: uestc_temperature_report

on:
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: "0 16 * * *" # cron表达式

env:
  TZ: 'Asia/Shanghai'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Run Main
      run: go run main.go -cookie=${{ secrets.COOKIE }}
